[package]
name = "capture-scheduler"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "1.8.0", features = ["v4"] }
anyhow = "1.0.82"
thiserror = "1.0.61"
dirs = "5.0.1"

